Fixes #31012 - API for retrieving outputs for multiple hosts
theforeman/foreman_remote_execution pull request #543
Opened 2020-10-07 15:00 UTC by adamruzicka

2020-10-07 21:54 UTC, ezr-ondrej commented
It seems we don't have permission for the new action

2020-10-08 09:20 UTC, adamruzicka commented
We do now

2020-10-14 16:08 UTC, ezr-ondrej reviewed
Just two points to discuss, by no means blockers. Apart of those this LGTM :+1: 

- Would `outputs` be descriptive enough given it's quite straight forward what outputs we mean. The `bulk_outputs` invokes for me that it's gonna be outputs of more jobs.
- Should we have `bulk_raw_outputs` / `raw_outputs` as well ?

2020-10-15 07:29 UTC, adamruzicka commented
> Would outputs be descriptive enough given it's quite straight forward what outputs we mean. The bulk_outputs invokes for me that it's gonna be outputs of more jobs.

Possibly, `bulk_outputs` was more of a working name that somehow stuck.

> Should we have bulk_raw_outputs / raw_outputs as well ?

I don't really like the split between `output` and `raw_output`. What if for `bulk_outputs`/`outputs` it was just another parameter, defaulting to false?

2020-10-15 08:28 UTC, ezr-ondrej commented
> Possibly, `bulk_outputs` was more of a working name that somehow stuck.

So should we rename it before merging? :thinking: 

> I don't really like the split between `output` and `raw_output`. What if for `bulk_outputs`/`outputs` it was just another parameter, defaulting to false?

Yeah, that sounds good to me :+1:

2020-10-15 08:43 UTC, adamruzicka commented
Will do both of the changes

2020-10-15 09:48 UTC, ezr-ondrej reviewed
Just places with forgotten renaming, apart of it, LGTM :+1:

2020-10-15 09:48 UTC, ezr-ondrej commented on app/controllers/api/v2/job_invocations_controller.rb
> +      before_action :find_resource, :only => %w{show update destroy clone cancel rerun bulk_outputs}
```suggestion
      before_action :find_resource, :only => %w{show update destroy clone cancel rerun outputs}
```

2020-10-15 09:48 UTC, ezr-ondrej commented on app/controllers/api/v2/job_invocations_controller.rb
> +        when 'output', 'raw_output', 'bulk_outputs'
```suggestion
        when 'output', 'raw_output', 'outputs'
```

2020-10-15 09:48 UTC, ezr-ondrej commented on test/functional/api/v2/job_invocations_controller_test.rb
> +      describe '#bulk_outputs' do
```suggestion
      describe '#outputs' do
```

2020-10-15 09:48 UTC, ezr-ondrej commented on test/functional/api/v2/job_invocations_controller_test.rb
> +          get :bulk_outputs, params: { :id => @invocation.id, :search_query => "name = definitely_not_in_the_job" }
```suggestion
          get :outputs, params: { :id => @invocation.id, :search_query => "name = definitely_not_in_the_job" }
```

2020-10-15 09:48 UTC, ezr-ondrej commented on test/functional/api/v2/job_invocations_controller_test.rb
> +          get :bulk_outputs, params: { :id => @invocation.id }
```suggestion
          get :outputs, params: { :id => @invocation.id }
```

2020-10-15 11:05 UTC, adamruzicka commented
I thought I probably missed a place or two, but didn't expect this many

2020-10-15 15:08 UTC, ezr-ondrej requested changes
Just one more find from testing.

2020-10-15 15:08 UTC, ezr-ondrej commented on app/controllers/api/v2/job_invocations_controller.rb
> +            .merge(id: host.id)
Sorry for not noticing sooner, but while testing it, I've realized `outputs: [{...., id: 1}]` is quite missleading. First sight it seems like an ID of the output. Should we use `host_id` instead to be more explicit?
```suggestion
            .merge(host_id: host.id)
```

2020-10-15 15:12 UTC, ezr-ondrej commented
And one more in the `raw = true`:
We are using `join` without delimiter, so the output is one line.
Should we use `output.map { |set| set['output'] }.join("\n")` instead?

2020-10-19 10:06 UTC, adamruzicka commented
The partial outputs should be ending with newlines so if we join it without any delimiter, it should appear the same way as it was originally produced by the command

2020-10-20 09:15 UTC, ezr-ondrej commented
> The partial outputs should be ending with newlines so if we join it without any delimiter, it should appear the same way as it was originally produced by the command

It was not the case for me, but it is quite likely I was just doing something wrong :+1: I'll retest it.
What about the `host_id` in the output? Should we do something about it?

2020-10-20 09:31 UTC, adamruzicka commented
> What about the host_id in the output? Should we do something about it?

Applied your suggestion just now

2020-10-20 10:00 UTC, adamruzicka commented
And need to fix the tests

2020-10-20 21:43 UTC, ezr-ondrej requested changes
Apart of a documentation typo, works nice :+1:
I was just using bad json parser, that ate the newlines from the raw output :)

2020-10-20 21:43 UTC, ezr-ondrej commented on app/controllers/api/v2/job_invocations_controller.rb
> +      api :GET, '/job_invocation/:id/outputs', N_('Get outputs of hosts in a job')
The first time around I though "why have I used singular here, we are not github", second time "something is odd".
I've figured that while checking the `/apidocs` Turns out I've been following the documentation without even knowing it xD
```suggestion
      api :GET, '/job_invocations/:id/outputs', N_('Get outputs of hosts in a job')
```

2020-10-21 08:23 UTC, ezr-ondrej approved these changes
Thanks @adamruzicka ! :+1:

2020-10-21 08:26 UTC, merged