Refs #31267 - align recent jobs card to the design
theforeman/foreman_remote_execution pull request #596
Opened 2021-06-03 15:50 UTC by amirfefer

![Screen Shot 2021-06-03 at 18 43 16](https://user-images.githubusercontent.com/11807069/120674227-90e80880-c49c-11eb-9e09-acb5b0d2a58a.png)

2021-06-10 08:15 UTC, adamruzicka requested changes
Looks nice, but lints are failing

2021-07-05 16:32 UTC, amirfefer commented
@adamruzicka, thanks.
Updated

2021-07-15 12:08 UTC, xprazak2 commented
Ruby test failures seem unrelated.

2021-07-16 13:00 UTC, adamruzicka requested changes
One thing I noticed.

Also could you rebase? It should resolve the ruby test failures

2021-07-16 13:00 UTC, adamruzicka commented on webpack/react_app/components/RecentJobsCard/constants.js
> +  '/api/job_invocations?order=start_at+DESC&search=targeted_host_id%3D$';
I think the dollar at the end shouldn't be there. Or at least on my machine I see requests like `http://localhost:3000/api/job_invocations?order=start_at DESC&search=targeted_host_id=$8` and there's no host with ID `$8`

2021-07-22 00:53 UTC, amirfefer commented
Thanks @adamruzicka ! fixed :)

2021-07-23 09:43 UTC, adamruzicka commented
If there are no jobs, it simply shows nothing. Shouldn't there be something like a miniature empty state or something? I'm not instisting on it, just curious.

![image](https://user-images.githubusercontent.com/7326770/126764522-807f8404-20e4-46c9-a84f-6723e9d6adb1.png)

2021-07-25 23:20 UTC, amirfefer commented
Thanks @adamruzicka, done
![Screen Shot 2021-07-26 at 2 20 08](https://user-images.githubusercontent.com/11807069/126916591-334363ce-b220-4d68-87d9-c02605f35425.png)

2021-07-27 14:28 UTC, adamruzicka approved these changes
Looks nice, ACK

2021-07-27 14:28 UTC, merged

2021-07-27 14:28 UTC, adamruzicka commented
Thank you @amirfefer !