Fixes #33737 - Add bookmarks to templates in job wizard
theforeman/foreman_remote_execution pull request #678
Opened 2021-12-22 18:02 UTC by MariaAga

Now when a user has a search input field in the template they can use it's bookmarks.
(Before the foreman fix the new bookmark modal will choose only the last text entered as the value so we can only had one bookmark button perpage)
![Screenshot from 2021-12-22 19-01-31](https://user-images.githubusercontent.com/30431079/147135811-a2bcf746-4040-4a88-849b-554ee60a47e0.png)

2022-01-05 13:23 UTC, adamruzicka requested changes
This acts in a slightly weird way. I created a job template with type=search and and resource=host. If I try to fill this input using a bookmarks, it shows me no bookmarks. Looking under the hood it does a request to `/api/bookmarks?search=controller%3DHost` which yields no results. If I go to the hosts index page and one the bookmarks there, it does the request to `http://localhost:3000/api/bookmarks?search=controller%3Dhosts` (`Host` vs `hosts`). We might need to do some kind of mapping there

2022-01-05 16:26 UTC, MariaAga commented
Thanks! should work now

2022-01-06 11:52 UTC, adamruzicka requested changes
When I select one of the bookmarks, it redirects me to the form again and sets `search` param to the search query of the bookmark. That's probably not what we want

2022-01-06 18:06 UTC, MariaAga commented
ok now it should work!
There is a bug in foreman, as it's unusual for the page to not refresh, the dropdown doesn't close on select, will fix in foreman https://projects.theforeman.org/issues/34228

2022-01-07 12:06 UTC, adamruzicka commented
If I understand it correctly, the search fields try to do autocompletion, but they do not honor the controller of the resource.

Here we have the form querying `/hosts/auto_complete_search` for job invocations:
![image](https://user-images.githubusercontent.com/7326770/148541730-75f7b9cc-8339-4797-8a06-4695fdac4edf.png)

This leads to errors being shown, even though the search query is in fact correct

![image](https://user-images.githubusercontent.com/7326770/148541585-fcc2dea6-26e5-4be8-b60c-574e3bce69e9.png)

2022-01-07 12:53 UTC, MariaAga commented
Forgot to mention, this pr should be tested with https://github.com/theforeman/foreman/pull/8922

2022-01-07 14:05 UTC, MariaAga commented
Thanks @adamruzicka! fixed!

2022-01-07 16:39 UTC, adamruzicka approved these changes
Works well

2022-01-07 16:40 UTC, merged

2022-01-07 16:40 UTC, adamruzicka commented
Thank you @MariaAga !