Fixes #35437 - host details jobs change from list to table
theforeman/foreman_remote_execution pull request #752
Opened 2022-08-26 07:19 UTC by MariaAga

Its more correct to use table in this case and its easier for qe to test

2022-09-01 07:35 UTC, adamruzicka requested changes

2022-09-01 07:35 UTC, adamruzicka commented on webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
> +          {jobs?.length &&
If there are no jobs, the card just says `0`
![image](https://user-images.githubusercontent.com/7326770/187858013-811e68c5-74b0-4797-bcc9-468ef193efe1.png)

Maybe `map`-ing over an empty array should be valid

2022-09-01 11:54 UTC, adamruzicka commented
Also needs a rebase

2022-09-02 08:37 UTC, MariaAga commented
rebased and fixed the 0 issue by moving `jobs?.length` up in the tree to trigger the empty state message

2022-09-02 11:12 UTC, adamruzicka approved these changes
ACK

2022-09-02 11:12 UTC, merged

2022-09-02 11:12 UTC, adamruzicka commented
Thank you @MariaAga !