Fixes #36837 - Template for convert2rhel analyze
theforeman/foreman_remote_execution pull request #840
Opened 2023-10-16 15:58 UTC by stejskalleos

2023-10-17 06:59 UTC, stejskalleos commented
@adamruzicka review please

2023-10-17 11:29 UTC, stejskalleos commented
Updated
* Check for RH OS family
* root check
* installing tool if not present
* if any errors or warnings are present, exit 1

How to install the tool: https://developers.redhat.com/articles/2023/04/11/how-use-convert2rhel-migrate-centos-rhel?source=sso

2023-10-17 11:37 UTC, stejskalleos commented on app/views/templates/script/convert2rhel_analyze.erb
> +    echo "Error: $errors error(s) have been found."
I just realized that the $errors will be always 1 or 0, as the `json` file is one line only.

2023-10-17 12:05 UTC, adamruzicka reviewed
A suggestion to make things a bit simpler if we can't get the counts anyway

2023-10-17 12:05 UTC, adamruzicka commented on app/views/templates/script/convert2rhel_analyze.erb
> +    echo "Warning: $skips check(s) have been skipped."
```suggestion
if ! grep -q SKIP /var/log/convert2rhel/convert2rhel-pre-conversion.json; then
    echo "Warning: Some check(s) have been skipped."
```

2023-10-17 12:05 UTC, adamruzicka commented on app/views/templates/script/convert2rhel_analyze.erb
> +    echo "Error: $errors error(s) have been found."
```suggestion
if ! grep -q ERROR /var/log/convert2rhel/convert2rhel-pre-conversion.json; then
    echo "Error: Some error(s) have been found."
```

2023-10-23 07:36 UTC, adamruzicka requested changes

2023-10-23 07:36 UTC, adamruzicka commented on app/views/templates/script/convert2rhel_analyze.erb
> +if ! [ $(id -u) = 0 ]; then
`=` in test does string-based comparison. I'd rather be explicit and use `-eq` to do numeric comparison

2023-10-23 07:36 UTC, adamruzicka commented on app/views/templates/script/convert2rhel_analyze.erb
> +errors=$(grep -c 'ERROR' '/var/log/convert2rhel/convert2rhel-pre-conversion.json')
Why is this still here?

2023-10-23 09:20 UTC, adamruzicka approved these changes

2023-10-23 09:20 UTC, merged