Fixes #38090 - Add filtering to job invocation hosts table
theforeman/foreman_remote_execution pull request #934
Opened 2024-12-12 09:55 UTC by kmalyjur

Sorting and filtering were added to the host table of the new job invocation page.
(Ordering by status is not permitted on purpose.)

TODO:
- [ ] Check if there is no unnecessary reloading of the page
- [ ] Pagination resets the filter
- [ ] If page=2 is set in the URL but only 1 page of results exists, auto-correct to page=1 to avoid the "no results" message
- [ ] Wrap each row in tbody (needed for future additions)

2025-01-21 09:53 UTC, MariaAga requested changes
This works almost perfectly, and its nice that the chart also searchs the table, only a few comments?

2025-01-21 09:53 UTC, MariaAga commented on webpack/JobInvocationDetail/JobInvocationConstants.js
> +  CANCELLED: { id: 'cancelled', title: __('Canceled') },
Canceled should have 2 Ls -> Cancelled (both right, but we use the 2 L one in REX)

2025-01-21 09:53 UTC, MariaAga commented on webpack/JobInvocationDetail/JobInvocationHostTable.js
> +        : '';
@adamruzicka Is it correct to filter `/api/job_invocations/53/hosts?search=` with  `job_invocation.id = 53 and job_invocation.result = success and (name ~  centos9 )` ? It does provide the correct results

2025-01-21 09:53 UTC, MariaAga commented on webpack/JobInvocationDetail/JobInvocationHostTable.js
> +      params: { search: searchQuery },
Should include the filter search as well, for example if you select a status and then search the status is not included in the search but still shown as selected

2025-01-21 10:10 UTC, adamruzicka commented on webpack/JobInvocationDetail/JobInvocationHostTable.js
> +        : '';
It is a bit counter-intuitive, but this indeed seems to be the right way. I was thinking about dropping the `job_invocation.id = 53`, but looking at the sql that would generate we would get hosts which were in this job, but succeeded in another.

2025-01-21 15:47 UTC, kmalyjur commented on webpack/JobInvocationDetail/JobInvocationConstants.js
> +  CANCELLED: { id: 'cancelled', title: __('Canceled') },
Nice catch :smile:

2025-01-21 17:05 UTC, kmalyjur commented
I also removed the custom pagination from the `Table` as @MariaAga found out the usage of `setParams` is enough.

2025-01-21 18:08 UTC, MariaAga commented on webpack/JobInvocationDetail/JobInvocationHostTable.js
this creates a second api call, best to use the new one :)

2025-01-21 18:57 UTC, MariaAga commented on webpack/JobInvocationDetail/JobInvocationHostTable.js
nope my bad, something else is causing the second api call

2025-01-24 16:00 UTC, adamruzicka commented
![image](https://github.com/user-attachments/assets/5cf187b3-2d52-4e5a-92cf-558172dc5ca8)

![image](https://github.com/user-attachments/assets/0ada13e1-9713-4742-88dd-59f8a9e64af9)

It is a bit unfortunate to map "running" to "Pending" and "pending" to "pending" with lowercase p and a different icon. Does the design say anything about this?

2025-01-25 20:39 UTC, kmalyjur commented
@adamruzicka We don't have anything about it in the design, actually. You're right, it looks bad, I'll change it.

2025-01-27 10:08 UTC, kmalyjur commented
- I added the code @MariaAga wrote for fixing the second unneeded API call
- @adamruzicka `running` and `pending` are both mapped to "Pending" now

The PR should be ready to be merged

2025-01-27 12:33 UTC, MariaAga commented
Running jobs dont show hosts, so merging should wait until we see if its the pr or just my env

2025-01-27 12:34 UTC, MariaAga commented
`job_invocation.id=ID` shows 0 results if the job is running

2025-01-27 12:39 UTC, kmalyjur commented
@MariaAga I can see them :thinking: 
![image](https://github.com/user-attachments/assets/161ffe56-e157-4fc6-b804-cea0273be03b)

2025-01-27 13:17 UTC, adamruzicka commented
Sadly, yes, the per-host tasks are not created until the job starts running, which makes it a little bit tricky.

2025-01-28 15:33 UTC, adamruzicka commented
js tests are red :/

2025-01-28 16:09 UTC, MariaAga commented
js test error make no sense, and dont happen locally, maybe re run them?

2025-01-28 16:24 UTC, adamruzicka approved these changes

2025-01-28 16:24 UTC, merged

2025-01-28 16:24 UTC, adamruzicka commented
Thank you @kmalyjur & @MariaAga !