[WIP] Registration - Show warning for Pull provider
theforeman/foreman_remote_execution pull request #936
Opened 2024-12-19 07:59 UTC by stejskalleos

WIP: Ongoing discussion in [SAT-22062](https://issues.redhat.com/browse/SAT-22062)

Screenshot:
![pull](https://github.com/user-attachments/assets/1a27d5b3-6944-4437-abfb-56fedba27ec2)

2025-01-08 12:31 UTC, stejskalleos commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that the Smart Proxy is configured correctly for the Pull provider.'
@Lennonka text review please

2025-01-08 13:34 UTC, Lennonka commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that the Smart Proxy is configured correctly for the Pull provider.'
Can we use a variable instead of `Smart Proxy` so that it says `Capsule` in Satellite?

2025-01-08 13:36 UTC, Lennonka requested changes

2025-01-08 13:36 UTC, Lennonka commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that the Smart Proxy is configured correctly for the Pull provider.'
```suggestion
        'Please make sure that Smart Proxy is configured for pull-based remote execution.'
```

2025-01-08 14:19 UTC, Lennonka commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that Smart Proxy is configured for pull-based remote execution.'
@stejskalleos Can we use a variable instead of `Smart Proxy` so that it says `Capsule` in Satellite?

2025-01-08 14:32 UTC, jeremylenz commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that Smart Proxy is configured for pull-based remote execution.'
`Smart Proxy` will automatically be translated to `Capsule` by foreman_theme_satellite.

2025-01-08 14:34 UTC, Lennonka commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +        'Please make sure that Smart Proxy is configured for pull-based remote execution.'
Oh, cool!

2025-01-09 07:33 UTC, stejskalleos commented
@adamruzicka ready for review

2025-01-13 14:18 UTC, adamruzicka reviewed
Also redmine check isn't happy

2025-01-13 14:18 UTC, adamruzicka commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +    </Alert>
Could we show this conditionally to avoid situations like the one below?

![image](https://github.com/user-attachments/assets/2502a7e7-db25-4208-8ab0-1654cf8e52b4)

2025-01-14 07:30 UTC, stejskalleos commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +    </Alert>
Okay, will add the conditions

2025-01-21 06:47 UTC, stejskalleos commented
aaand it's :green_apple:

2025-01-21 06:49 UTC, stejskalleos commented on webpack/react_app/components/RegistrationExtension/RexPull.js
> +function showPullWarning(valueFromParam, value) {
Note: The `if` branching might look weird at first glance, but it's because of:

`valueFromParam` can be `true`, `false` or `undefined`
`value` can be `'true'`, `'false'`, `''` or `undefined`.

It was fun.

2025-01-21 11:38 UTC, adamruzicka approved these changes

2025-01-21 11:39 UTC, merged